---
- name: Initialize Kubernetes cluster on master nodes
  hosts: controlplane
  become: yes
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address=192.168.56.15 --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Set up kubeconfig for auget user
      block:
        - name: Create .kube directory for auget
          file:
            path: /home/auget/.kube
            state: directory
            owner: auget
            group: auget
            mode: '0755'

        - name: Copy admin config to auget home
          copy:
            src: /etc/kubernetes/admin.conf
            dest: /home/auget/.kube/config
            remote_src: yes
            owner: auget
            group: auget
            mode: '0600'

    - name: Install a pod network add-on (Flannel)
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: kubeadm_init.changed
      environment:
        KUBECONFIG: /home/auget/.kube/config
      become_user: auget

    - name: Generate join command and save to file
      when: kubeadm_init.changed
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Save join command to local file
      when: kubeadm_init.changed
      delegate_to: localhost
      copy:
        content: "{{ join_command.stdout }}"
        dest: "./join-command.txt"
      become: no