---
- name: Join worker nodes to Kubernetes cluster
  hosts: worker1,worker2,worker3
  become: yes
  vars:
    join_command: "{{ lookup('file', './join-command.txt') }}"
  tasks:
    - name: Join node to Kubernetes cluster
      command: "{{ join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf