---
all:
  children:
    vbox:
      hosts:
        controlplane:
          ansible_host: 127.0.0.1
          ansible_port: 2222
        worker1:
          ansible_host: 127.0.0.1
          ansible_port: 2223
        worker2:
          ansible_host: 127.0.0.1
          ansible_port: 2224
        worker3:
          ansible_host: 127.0.0.1
          ansible_port: 2225
